[package]
name = "native-relay"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt", "io-util", "net", "sync", "macros"] }
native_messaging = { version = "0.2.0" }

[profile.release]
lto = true
strip = true
